services:
  pull:
    build: .
    env_file: .env
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    user: "${UID:-1000}:${GID:-1000}"
    environment: ["PYTHONUNBUFFERED=1"]

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    container_name: strava-scheduler
    environment:
      - TZ=Europe/London
    volumes:
      - ./:/repo
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /repo
    restart: unless-stopped
