services:
  pull:
    build: .
    env_file: .env
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    user: "${UID:-1000}:${GID:-1000}"
    environment: ["PYTHONUNBUFFERED=1"]

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    container_name: strava-scheduler
    environment:
      - TZ=Europe/London
      - HOST_REPO=${PWD}                    # <- absolute host path injected by Compose
    working_dir: /repo
    volumes:
      - ./:/repo                           # repo at /repo (for scripts/cron)
      - ${PWD}:${PWD}                       # <- same repo mounted at the *host* absolute path
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/repo/cron/strava.cron"]
    restart: unless-stopped


